# NUMPY 
creating arrays


In [2]:
import numpy as np
arr = np.array([1,2,3])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3]


In [9]:
zeros_arr=np.zeros((2,3))
ones_arr=np.ones((3,2))
#zeros_arr
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
arange_arr=np.arange(0,10,2)
#linspace_arr =np.linspace(0,1,5)
arange_arr

array([0, 2, 4, 6, 8])

In [13]:
arange_arr =np.arange(0,10,2)
linspace_arr =np.linspace(0,4,5)
linspace_arr

array([0., 1., 2., 3., 4.])

In [14]:
random_arr =np.random.rand(2,3)

In [15]:
print(random_arr)

[[0.15739349 0.57721958 0.47130405]
 [0.33939311 0.7563996  0.59509433]]


# ARRAY INDEXING AND SLICING
* accessing and modifying elements:
- use square brackets to access elements of an array
- modify elements by assigning new values.


In [16]:
arr= np.array([1,2,3,4,5])
print(arr[2])
arr[1]=10


3


In [17]:
print(arr[1])

10


In [3]:
rand_arr=np.random.randint(low=3,size=(2,3))
rand_arr

NameError: name 'np' is not defined

In [4]:
print("s")

s
