# array shape and reshape


In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6


In [6]:
type(arr)

numpy.ndarray

In [9]:
arr_1=np.arange(1,13)

In [10]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
reshaped_arr_1=arr_1.reshape((2,2,-1))

In [23]:
reshaped_arr_1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr_2= reshaped_arr_1.reshape(1,-1)

-1 daal do direct


In [30]:
arr_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [31]:
reshaped_arr_1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
for  i in arr_2:
  print(i)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [37]:
for i in arr_2:
    print(i)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
for  i in reshaped_arr_1:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [42]:
for elem in np.nditer(reshaped_arr_1):
    print(elem)

1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
arr=np.array([1,2,3])
sin_arr =np.sin(arr)

In [53]:
sin_arr

array([0.84147098, 0.90929743, 0.14112001])

In [54]:
matrix_a =np.array([[1,2], [3,4]])
matrix_b= np.array([[5,6], [7,8]])
result = np.dot(matrix_a, matrix_b)

In [55]:
result

array([[19, 22],
       [43, 50]])

In [56]:
##1. searching an element in an array
##2. finding largest number in an array.
##3. finding smallest number in an array.
##4. reversing an array.
##5. rotating an array by kth position.